[DET-2039] Decoupling code climate from coverage
travelaudience/orbs pull request #136
Opened 2023-01-04 12:12 UTC by dasphillipbrau

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] All new Jobs, Commands, Executors, Parameters have descriptions
- [ ] If PR adds a new feature, Examples have been added
- [ ] README has been updated, if necessary

2023-01-04 13:11 UTC, jobegrabber requested changes
Please put [these steps](https://github.com/travelaudience/orbs/pull/136/files#diff-89883f4ceb7c4b814a912a52ff6ded8afdbbe9a2b9588b44001bcc63c7462231R41-R44) under the condition, too.

[These steps](https://github.com/travelaudience/orbs/pull/136/files#diff-89883f4ceb7c4b814a912a52ff6ded8afdbbe9a2b9588b44001bcc63c7462231R80-L86) we also want to run without CodeClimate

2023-01-04 15:00 UTC, dasphillipbrau commented on src/scala/jobs/run_tests.yaml
> +  - run:
Good catch

2023-01-06 15:12 UTC, jobegrabber commented on src/scala/commands/test.yaml
> +        - equal: [ false, << parameters.with_coverage >>]
Could you try this?

```suggestion
        - << parameters.with_code_climate >>]
        - not: << parameters.with_coverage >>
```

2023-01-06 15:13 UTC, jobegrabber commented on src/scala/commands/test.yaml
> +                  cc_test_reporter_path: /tmp/code-climate
these are nested steps, right? interesting that it seems to work :)

2023-01-06 16:29 UTC, jobegrabber approved these changes

2023-01-10 10:55 UTC, merged