DEVOPS-1447 Helm 3 migration
travelaudience/orbs pull request #95
Opened 2021-05-04 10:42 UTC by bpietraga

**What this PR does / why we need it**:

- Move orb setup from supporting version 2 to Helm 3
- Depreciate the Helm 2 support
- Update dependencies for helm

**Special notes for your reviewer**:

**If applicable**:
- [ x ] All new Jobs, Commands, Executors, Parameters have descriptions
- [ x ] If PR adds a new feature, Examples have been added
- [ x ] README has been updated, if necessary

2021-05-04 12:45 UTC, cmoroianu1 commented on src/helm/commands/lint.yaml
> +          echo "a8ddb4e30435b5fd45308ecce5eaad676d64a5de9c89660b56face3fe990b318  helm-v3.5.4-linux-amd64.tar.gz" | sha256sum -c && \
👍

2021-05-04 12:48 UTC, cmoroianu1 commented on src/helm/commands/lint.yaml
> +          rm -f "helm-v2.17.0-linux-amd64.tar.gz"
why do all of these say v2.17.0 instead of v3.5.4

also why not set a variable with the version, like:
```
export HELM_VERSION="v...'
```

2021-05-04 12:49 UTC, cmoroianu1 commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@0.2.0
why not make it major:
1.0.0

2021-05-04 16:47 UTC, bpietraga commented on src/helm/commands/lint.yaml
> +          echo "a8ddb4e30435b5fd45308ecce5eaad676d64a5de9c89660b56face3fe990b318  helm-v3.5.4-linux-amd64.tar.gz" | sha256sum -c && \
Good eye 😄 - [FIXED](https://github.com/travelaudience/orbs/commit/3732e9dd70f8519bee6dd23abfa565aa20367f5c)

2021-05-04 16:53 UTC, bpietraga commented on src/helm/commands/lint.yaml
> +          rm -f "helm-v2.17.0-linux-amd64.tar.gz"
I've went a step further 🙂 https://github.com/travelaudience/orbs/pull/95/commits/4a96878a0b4fd2669c5d64b117d627b943953825

2021-05-04 16:54 UTC, bpietraga commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@0.2.0
Thank you @cmoroianu1 

I was wondering why it is in the example folder. Maybe we should move it somewhere else, as it is used in real orb release process?

2021-05-04 16:54 UTC, bpietraga commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@0.2.0
https://github.com/travelaudience/orbs/pull/95/commits/84ff1335902409aa9ffe4d351e5caf7acf8946c3

2021-05-05 08:20 UTC, FlavioF requested changes
Did you test this PR? Can you test it?

2021-05-05 08:20 UTC, FlavioF commented on src/helm/commands/lint.yaml
> +        curl -LO "https://get.helm.sh/helm-<<parameters.helm_version>>-linux-amd64.tar.gz" && \
we dont need this hack anymore since we are now using the proper helm version inside the helm test executor

2021-05-05 08:20 UTC, FlavioF commented on src/helm/commands/package.yaml
> +        curl -LO "https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz" && \
we dont need this hack anymore

2021-05-05 08:20 UTC, FlavioF commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@1.0.0
do we need a major version?

2021-05-05 15:45 UTC, bpietraga commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@0.2.0
Finally it will be minor version, which is not following semantic versioning, but it will enable us to roll this out without changing yaml files. Sorry for breaking change.

2021-05-05 15:47 UTC, bpietraga commented on src/helm/commands/package.yaml
> +        curl -LO "https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz" && \
Thank you @FlavioF !

2021-05-05 15:47 UTC, bpietraga commented on src/helm/commands/lint.yaml
> +        curl -LO "https://get.helm.sh/helm-<<parameters.helm_version>>-linux-amd64.tar.gz" && \
Thank you @FlavioF !

2021-05-05 15:47 UTC, bpietraga commented on src/helm/examples/package_and_push.yaml
> +    ta-helm: travelaudience/helm@1.0.0
Back to minor 👍

2021-05-06 09:34 UTC, bpietraga commented
@FlavioF

2021-05-06 15:25 UTC, FlavioF approved these changes

2021-05-06 18:08 UTC, merged

2021-05-06 18:09 UTC, bpietraga commented
> Did you test this PR? Can you test it?

Just as a note, the service has been tested in the 2 independent micro-services.